### ISSUE TITLE
Make data sources for Funnel Metrics

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#101]
Create Metrics with the [dost_metrics spreadsheet Engagement Data Source (Calendar Date) ](https://docs.google.com/spreadsheets/d/1oaC6QHrdA901UiDw8qAlbC2PzZ7GkM4_L1N8_QsIcXM/edit#gid=1921247872)

and 

Create Metrics with the [dost_metrics spreadsheet Engagement Data Source (User Age) ](https://docs.google.com/spreadsheets/d/1oaC6QHrdA901UiDw8qAlbC2PzZ7GkM4_L1N8_QsIcXM/edit#gid=1921247872)

**Comment by Satendra-SR** [comment]
### Todos

- [ ] Finalize the logic required for this.
- [ ] It needs multiple degrees of transformation and Datastudio is providing it to one degree. We need to pass pre-calculated data source:

1. Daily
2. Weekly
3. Monthly
4. Quarterly

**Comment by Satendra-SR** [comment]
Update points based on requirements

**Comment by rudresh** [comment]
Testing Feedback:
- [ ] Add `user_current_status` to all the funnel related data sources 
- [ ] Remove the records from `call_log_event` tables where `to_number` is not in the `system_phone` table
- [ ] June 1st data is not same in `daily_engagement_datewise` and `monthly_engagement_datewise`
- [ ] Validate logic for calculating `time_for_one_content`
- [ ] Verify why `user_age_on_call` comes in negative values for few records.
- [ ] user_id `168` is shown to be created on 1st week of april, but the data for week_number 12 is showing. As the user has not completed the 12 weeks, the records should not show up.
- [ ] Validate why and correct `weekly_engagement_useragewise` shows empty data for few weeks.

**Comment by rudresh** [comment]
@prtkdost @gandhisonia This is ready for testing. 
`user_age_on_call` is coming negative because of the time difference between when the user started getting the calls was earlier compared to their signup dates.

**Comment by Satendra-SR** [comment]
As accepted, closing now.
