### ISSUE TITLE
 backfilling missing users program tracking

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#260]
**Describe the bug**
1. There are users who us getting regular programs but their user_program is missing from the database.
2. There are a few users who are getting programs but their registration/user entry is missing.

**Add diagnosis details**
Diagnosis Report: https://docs.google.com/spreadsheets/d/19WvWXbq1J0CapAz6oO1I9MscmEJbZ_GC2dF2l5eCrkw/edit#gid=574765525

**Expected behavior**
1. Each user should've their user_program assigned
2. Each user should have their user and registration details in the application database

**Root cause**
1. We create the registration as soon as the user gives a missedcall, but the user and user program gets created after the user received the registration flows.
2. In the past, there are incidents where we have missed some webhooks callbacks. As the users get created in registration_flow only, in case it got missed, the user, registration, and user program details don't get populated.
Note: Not including the impact of missing incoming and outgoing calls data, which is targeted in another monitoring issue: https://github.com/DostEducation/analytics-datasources/issues/43#issuecomment-1102490269 

**Update based on 25th April call data sample**
There is 433 user who gave missed call but their user program is not added to the system. Check out the report here.
https://docs.google.com/spreadsheets/d/1VTXMORhWWsmfjiKuUVR-uD9OUHo2gBJzKpQkrFNgYS4/edit#gid=55864945

**Impact**
1. There is an overall **433** (based on the 25th diagnosis) user in our database who doesn't have a user_program entry in the application database.
2. There are 3 users who don't have an entry in the registration and user table.
More [details here](https://docs.google.com/spreadsheets/d/19WvWXbq1J0CapAz6oO1I9MscmEJbZ_GC2dF2l5eCrkw/edit#gid=0)

- Total unique missedcall phone number - **35856**
- Total unique users who have a user program in the database - **35401**
- Missing records - **455**
- Percentage of missing users - **1.26**

**Criticality**
- medium

**Action items**
- [ ] Backfill these user's data in 
    - [ ] User table
    - [ ] user_program table
    - [ ] Registration table (if any)
    - [ ] Make sure the data is migrated to BigQuery
- [ ] Create user and user program as soon as user give a missed call - https://github.com/DostEducation/RP_IVR_analytics/issues/237

**Comment by Satendra-SR** [comment]
### Updates on this based on 25th call data:

**Diagnosis report:**
https://docs.google.com/spreadsheets/d/1VTXMORhWWsmfjiKuUVR-uD9OUHo2gBJzKpQkrFNgYS4/edit#gid=574765525

**Comment by Satendra-SR** [comment]
Updated the estimates based on the overall number of users we have without a user and user program

**Comment by GauravGusain98** [comment]
This is very old data and now this task is obsolete. Purgin this.

**Comment by Satendra-SR** [comment]
THis is purged issue, closing now
