### ISSUE TITLE
Remove the modules related to `dry-flow` from the service

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#468]
**Is your feature request related to a problem? Please describe.**
We have removed the `Data-sync dry-flow` from the Rapaidpro and now we are not getting any kind of data from this flow type. So, now we can remove the extra code and database schema related to the `dry-flow`.

**Describe the solution you'd like**
- [x] Check the code related to the `dry-flow`.
- [x] Check the tables and columns in the database related to the `dry-flow`.
- [x] Remove the extra code and database schema.
- [x] Create migrations for the database-related changes.
- [x] Do changes in the data migration service for database-related changes.
- [x] Test all the functionalities in the service.
- [x] Testing and deployment.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] All the extra code or database schema related to this should be removed.
- [x] All the functionalities in the service should work fine.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
Closing the issue as completed and on production now.

**Comment by Sachinbisht27** [comment]
**Events that happened in this particular story:**
- List down the features that are not in use.
  - **User Group Service:** [To store the latest user  groups of the user.]
  - **User Custom Field Service:** [To store all the custom fields and values of the users.] 
  - **User Custom Field Mapping:** [To check and update the default values in the columns of other tables.]
- Discuss with the team to confirm whether these features are required or not.
- Removed the functionality to store the user groups in the database.
- Removed the functionality to store custom fields from the database.
- Removed the functionality to update the mapped field based on the values of the active custom fields.
- Generation of the migrations for the removal of the tables related to the functionalities and the database schema changes.
- Testing for all the changes and the functionalities related to the `dry-flow`. [Locally, and in Staging environment]
- We have archived all the data from the application database before release.
- Then there were some changes required on the Data-Migration- Service to stop the migration for the tables that we had removed from the application database.
- The release of the changes in the Production environment of RP_IVR and Data-Migration-Service.

**Comment by Sachinbisht27** [comment]
**Explanation in extra hours -**
1. The initial estimations for codebase changes did not fully account for the complexities involved in removing the specified features. 
2. We estimated 8 hours for this issue but encountered some challenges during implementation.
3. We have listed down the functionalities that we have to remove and communicated with the team before starting the development which combined took 1 hour as estimated.
4. We have performed all the codebase changes and that was completed in 6 hours as estimated.
5. But the testing for the changes was initially estimated at 1 hour. However, the testing of the other functionalities related to this feature took 2 hrs more time than we estimated as those changes are affecting the unsubscribing functionality.
6. Usually we create separate tickets for a few actions, such as those related to the Data Archival Service and Data-Migration-Service, we opted to address them within this issue which took us an extra 8 hours other than estimations.
7. We invested 2 hours in manually archiving data from the application database to BigQuery to ensure the transition and preservation of the historical data.
8. We modified the Data-Migration-Service to halt migration for removed tables which took 6 hours of effort, including codebase changes and the testing for the changes before deployment.
9. All the development and the extra changes we have done in this issue are mentioned in the history of the issue itself.
10. We have communicated the extra work done on this issue in stand-up and also tracked these hours in the CC timesheet but missed updating it on GitHub.

**Comment by Sachinbisht27** [comment]
### Details on the items that are done in the story:

#### Phase 1: At the application level - **8 hours**

- List down the features that are not in use, share them with the team and discuss to get confirmation on any dependent features to be unchanged- **1-hour**
- The overall development involved in the process  -  **6 hours**
    - https://github.com/DostEducation/RP_IVR_analytics/pull/470
- Database migrations to remove these database tables - **1 hour**
- As it involved system-wide impact, testing for all the changes and the functionalities related to the `dry-flow` like mapping tables, and un-subscribe functionality took additional efforts - **3 hours**
    - Mapping tables
    - Un-subscribe functionality

#### Phase 2: At the Data Archival Service - **3 hours**

- While discussing the progress in standup, we agreed upon archiving the data on BigQuery before removing the database tables. The activity happens before we release the changes to production.
- We have a data archival service which archives the older data (for specific tables) for future reference. However, the related tables were not a part of the data archival process earlier.


#### Phase 3: At the Data-Migration-Service - **8 hours**

- As we don't have the staging data migration pipeline and releasing changes on the production server is a bit risky as it can corrupt the last 3 years' data. So in a discussion, we decided to replicate the production database on a local machine and perform the complete data migration testing before we move any changes to production.
- The reasons for not having a staging data migration pipeline are
    - Additional recurring costs associated with it 
    - The limited usecase made us decide (back in 2022) to not invest in a staging server.
- We had to replicate the production database on the local machine to test the overall data migration. As the database size was huge (around 15 GB), it took time to take the backup and replicate the usecase.
- The trail for the changes - https://github.com/DostEducation/data-migration-service/pull/135/files

**Comment by Sachinbisht27** [comment]
**Explanation in extra hours -**
1. We estimated 8 hours as it was a module cleanup task to remove an existing functionality from the application and based on the listed functionality to be removed and tested.
2. During development, we found more areas that we thought should be cleandup but not related to the scope in estimations. 
3. We cleaned up those additional areas also, as we were working in the same module.
4. It should have been tracked as a seperate task, but in that moment it felt like it would be faster. Doing it later may have taken the same time if not more. The additional 11 hours I have added to the Github.
5. Here also, we were tracking these hours regularly on the same day in ColoredCow timesheet but missed updating it in GitHub. I verified the same dates entry in the CC timesheet via Google sheet history.
